# Generated by Django 5.2.3 on 2025-09-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_like_unique_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photo.post'),
        ),
    ]
